export const GET_CREDIT_CARD_INFO = "GET_CREDIT_CARD_INFO";
export const CHANGE_CARD_NUMBER = "CHANGE_CARD_NUMBER";
export const CHANGE_CARD_NAME = "CHANGE_CARD_NAME";
export const CHANGE_CARD_MONTH = "CHANGE_CARD_MONTH";
export const CHANGE_CARD_YEAR = "CHANGE_CARD_YEAR";
export const CHANGE_CARD_CVV = "CHANGE_CARD_CVV";

export const FLIP_CREDIT_CARD = "FLIP_CREDIT_CARD";
